# ETL PROJECT

In [ ]:
Datasource:
    File Name: 
Datasource:
    File Name:
    File Name:

## Extract, Transform, Load
   Steps:
   1. Retrieved the data from each source found on Kaggle.com and Data.world
   2. Downloaded files as .csv to Local Drive
   3. In Google Cloud (GC), new project created "all-about-that-database'
   4. (GC) Created new storage bucket 'nba' and folder 'resources'
   5. (GC) Uploaded .csv file to resources folder
   6. (GC) In project, new table schema created "nba"
   7. (GC) New tables created "INSERT NAMES HERE"
   8. (GC) New view created by joining "TABLE NAME" and "TABLE NAME" on "INSERT FIELD NAME' -
   #####note: This is for the salary information
       Reasoning:
   9. (GC) From "INSERT TABLE NAME" field names "INSERT FIELD NAMES" selected
   10. (GC) Final view created by joining "TABLE NAME" and "TABLE NAME" on "INSERT FIELD NAME"
       Reasoning:
   11. Exported "TABLE NAME" as .csv to Local Drive to push onto GitHub

In [2]:
import pandas as pd
csv = 'nba_final_data_output.csv'
data = pd.read_csv(csv)

In [8]:
data.columns

Index(['name', 'career_FG_', 'birthPlace', 'position', 'college',
       'career_FG3_', 'career_PTS', 'career_WS', 'career_PER', 'career_FT_',
       'career_AST', 'career_TRB', 'highSchool', 'team', 'season', 'salary',
       'Player', 'Date', 'Age', 'Weight', 'Height', 'Pre_draft_Team',
       'Draft_Year', 'Conference'],
      dtype='object')

In [18]:
# Field Names to be Adjusted:
    # career_FG_
    # birthPlace
    # career_FG3_
    # career_FT_
    # highSchool
    # name - drop
    # Date
    # Age
    # Weight
    # Height
    # Pre_draft_Team
    # Draft_Year
    # Conference

cleaned_names = data.rename(columns={'Player': 'player','career_FG_' : 'field_goal', 'birthPlace' : 'birth_place', 'career_FG3_' : 'three_ptr', 
                                      'career_FT_' : 'free_throw', 'highSchool': 'high_school', 'Date': 'date', 'Age': 'age', 
                                       'Weight' : 'weight', 'Height' : 'height', 'Pre_draft_Team': 'pre_draft_team', 'Draft_Year': 'draft_year',
                                       'Conference':'conference', 'career_PTS' : 'points', 'career_WS': 'win_share', 'career_PER': 'efficiency'})

In [25]:
cleaned_names

,field_goal,birth_place,position,college,three_ptr,points,win_share,efficiency,free_throw,career_AST,...,season,salary,player,date,age,weight,height,pre_draft_team,draft_year,conference
0,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,23-Mar-86,30,208,6'5,Notre Dame,1976,NaN
1,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,18-Mar-84,28,208,6'5,Notre Dame,1976,NaN
2,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,18-Dec-83,28,208,6'5,Notre Dame,1976,NaN
3,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,19-Oct-80,25,208,6'5,Notre Dame,1976,NaN
4,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,2-Dec-79,24,208,6'5,Notre Dame,1976,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,30-Nov-15,27,240,6'9,Texas,2007,West
15996,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,5-Jan-15,26,240,6'9,Texas,2007,West
15997,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,24-Mar-14,25,240,6'9,Texas,2007,West
15998,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,10-Feb-14,25,240,6'9,Texas,2007,West
15999,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,27-Jan-14,25,240,6'9,Texas,2007,West

In [26]:
del cleaned_names['name']

KeyError: 'name'

In [27]:
cleaned_names

,field_goal,birth_place,position,college,three_ptr,points,win_share,efficiency,free_throw,career_AST,...,season,salary,player,date,age,weight,height,pre_draft_team,draft_year,conference
0,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,23-Mar-86,30,208,6'5,Notre Dame,1976,NaN
1,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,18-Mar-84,28,208,6'5,Notre Dame,1976,NaN
2,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,18-Dec-83,28,208,6'5,Notre Dame,1976,NaN
3,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,19-Oct-80,25,208,6'5,Notre Dame,1976,NaN
4,54.0,"Washington, District of Columbia",Small Forward,University of Notre Dame,17.1,24.3,134.2,21.5,81.8,3.0,...,1984-85,515000,Adrian Dantley,2-Dec-79,24,208,6'5,Notre Dame,1976,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,30-Nov-15,27,240,6'9,Texas,2007,West
15996,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,5-Jan-15,26,240,6'9,Texas,2007,West
15997,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,24-Mar-14,25,240,6'9,Texas,2007,West
15998,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,10-Feb-14,25,240,6'9,Texas,2007,West
15999,49.3,"Washington, District of Columbia",Power Forward and Small Forward and Shooting G...,University of Texas at Austin,38.1,27.0,141.7,25.2,88.3,4.1,...,2015-16,20158622,Kevin Durant,27-Jan-14,25,240,6'9,Texas,2007,West